Add: products view, products urls RESTful 하게 구현
wecode-bootcamp-korea/31-1st-TheCreationOfWeb-backend pull request #10
Opened 2022-04-01 10:29 UTC by sangahnhan

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [x] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 카테고리, 제품 uri 를 통해 불러오기

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. CategoryView 구현 : uri 에서 categories/<int: category_id> 를 입력받아서 해당 카테고리에 해당하는 모든 제품의 이름, 가격, 이미지 준다
3. ProductView 구현 : uri 에서 categories/<int: category_id>/product/<int: product_id> 를 입력받아서 처음 카테고리 아이디에 해당하는 제품들을 순서대로 1번부터 번호를 붙여서 product_id로 해당 번호에 해당하는 제품의 상세 정보를 준다.

<br />

<br />

## :: 기타 질문 및 특이 사항

2022-04-01 21:52 UTC, lordmyshepherd reviewed
**피드백 3. 하나의 PR에는 하나의 기능만 올라올 수 있도록 두개를 각각 나눠서 올려주세요.** 
왜 그렇게 해야되는지도 고민해보시고 답변 남겨주시면 좋을 것 같습니다-!

- products 앱 view 와 products 앱 url 을 따로 나눠야 할것 같습니다. 그 이유는, 하나의 PR 에 하나의 기능만 들어가 있으면, 다른 리뷰어가 리뷰하기도 쉽고, 브랜치마다(PR마다) commit 을 관리하기도 쉽기 때문입니다.

2022-04-01 21:52 UTC, lordmyshepherd commented on products/views.py
> +        return JsonResponse({'product_list' : products_list} , status = 200)
**피드백 1.**
`CategoryView`의 목적이 input으로 받은 category_id에 해당하는 상품 목록을 반환하는 것이라면, `CategoryView`가 아니라 `ProductListView`가 되어야 합니다.
쉽게 생각하면, 반환하는 값이 어떤 데이터인지에 따라서 Class명이 정해져야 하는 것이죠.

지금은 CategoryView인데 정작 반환되는 데이터는 상품이 반환되고 있습니다.

아래와 같이 "상품" 기준으로 코드를 다시 작성해주세요. 
추가로 URI가 `categories/<int:category_id>`가 아니라 
`products?category_id=1`이 되도록 만들어주셔야 합니다.

```suggestion
class ProductListView(View):
    def get(self, request):
        category_id = request.GET.get(....)
        
        products = ..

        products_list = [{
            'name'  : product.name,
            'price' : product.price,
            'images': [image.image_url for image in product.picture_set.all()]
        } for product in products]

        return JsonResponse({'product_list' : products_list} , status = 200)
```

2022-04-01 21:52 UTC, lordmyshepherd commented on products/views.py
> +        return JsonResponse({'product_information' : product_information} , status = 200)
**피드백2.**
상품정보 하나를 반환하는 엔드포인트 인가요?
상품 정보 하나를 반환하는 엔드포인트라면, category_id를 받을 필요없이 product_id만 받아도 구현할 수 있습니다.
uri도 `products/1`이 되도록 수정해주세요.

line 20번 코드는 가독성이 좋지 않고 버그가 발생할 수 있는 가능성이 높은 코드 입니다.

**(1) 가독성이 안좋은 이유는 상품정보를 반환하는 로직인데 Category를 기준으로 로직이 작성된 점.**
**(2) 버그가 발생할 수 있는 가능성이 높고 디버깅하기 어려운 코드인 이유는 Category...product_set.all()을 통해서 여러개를 가져온 후에 여러개 중에 하나를 `[product_id - 1]`을 사용해서 빼주는 로직으로 product table에 데이터 순서만 바뀌어도 문제가 생깁니다.**

위에서 말씀드린 두가지 문제는 Product를 기준으로 코드를 작성하게 되면 개선할 수 있습니다.!

2022-04-02 05:54 UTC, sangahnhan commented on products/views.py
> +        return JsonResponse({'product_list' : products_list} , status = 200)
넵 수정했습니다

2022-04-02 05:54 UTC, sangahnhan commented on products/views.py
> +        return JsonResponse({'product_information' : product_information} , status = 200)
넵 수정했습니다!

2022-04-02 09:33 UTC, lordmyshepherd requested changes

2022-04-02 09:33 UTC, lordmyshepherd commented on products/views.py
> +            products    = category.product_set.all()
```suggestion
            products    = Product.objects.filter(category_id = category_id)
```

2022-04-02 09:33 UTC, lordmyshepherd commented on products/views.py
> +            products    = category.product_set.all()
말씀드린 것 처럼 Product 기준으로 코드 다시 수정해주세요~

2022-04-02 09:33 UTC, lordmyshepherd commented on products/views.py
> +            return JsonResponse({'message' : 'INVALID_PRODUCT_ID'} , status = 400)
http status code는 상황에 맞게 정확하게 사용해주세요!

```suggestion
            return JsonResponse({'message' : 'INVALID_PRODUCT_ID'} , status = 404)
```

2022-04-02 12:02 UTC, closed without merging