Add: CartView POST method 구현
wecode-bootcamp-korea/31-1st-TheCreationOfWeb-backend pull request #17
Opened 2022-04-05 01:26 UTC by mquat

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. Carts View  - Post 기능 구현 
-  'add to cart'를 클릭하면 해당 제품의 데이터가 서버에 전송 
-  이미 존재하는 경우 수량만 update 
-  새롭게 추가되는 경우 add 
-  데이터를 create 후, 클라이언트에는 해당 user 장바구니 summary(장바구니에 넣은 모든 제품) return  
2. Carts ursl.py 추가
3. fruitz_company urls.py에 carts 추가 
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- ORM 사용 시, get/filter를 어떤 상황에 사용하는게 더 적절한지 고민해볼 수 있었습니다. 
- update_or_create 메소드를 통해 update/add 기능을 한번에 구현해볼 수 있었습니다. 
- original 홈페이지의 장바구니 flow를 참고하면서, 사용자의 behavior/what data should be delivered 에 대해 더 배울 수 있었습니다
- 이전에 지적받았던 변수명 작성을 고민했습니다. (어떻게 naming해야 직관적이고 어떤 내용인지 쉽게 이해/구분 될 것인가?) 

<br />

## :: 기타 질문 및 특이 사항
- update_or_create 작성 시, 'obj, create' 부분에서 obj에 아무 이름이나 넣어도 통신이 되는데,
   이 obj에 정확히 어떤 내용을 넣어야 하는지 모르겠습니다. (공식문서를 봤는데도 이해가 잘...)

2022-04-05 02:10 UTC, mquat commented
main pull해서 conflict 수정했습니다!

2022-04-05 07:29 UTC, lordmyshepherd requested changes

2022-04-05 07:29 UTC, lordmyshepherd commented on carts/views.py
> +class CartView(View):
코드 리뷰
```python
    @login_decorator
    def post(self, request):
        try:
            data = json.loads(request.body)

            cart, created = Cart.objects.get_or_create(
                user       = request.user,
                product_id = data["product_id"],
                defaults   = {
                    'price' : data['price'],
                    'quantity': data['quantity']
                },
            )

            if not is_created:
                cart.quantity += data["quantity"]
                cart.save()

            carts = [{
                'image_url' : [image.image_url for image in item.product.picture_set.all()],
                'name'      : item.product.name,
                'price'     : item.price,
                'quantity'  : item.quantity 
            } for item in Cart.objects.filter(user=user)]

            return JsonResponse({'message':summary}, status=201)

        except KeyError:
            return JsonResponse({'message':'KEY_ERROR'}, status=400)
        except json.JSONDecodeError:
            return JsonResponse({'message':'JSON_DECODE_ERROR'}, status=400)
        except ValidationError as e:
            return JsonResponse({'message':e.message}, status=401)
```

2022-04-06 09:37 UTC, mquat commented
post 수정했습니다 병민님

2022-04-06 09:52 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2022-04-06 09:52 UTC, merged