Feature/models
wecode-bootcamp-korea/31-1st-TheCreationOfWeb-backend pull request #2
Opened 2022-03-29 08:39 UTC by mquat

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 전체 모델링 구현 완료 

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
* 회원가입: 아이디, 비밀번호, 주소, 핸드폰번호를 사용한 가입 기능 구현
* 로그인: 아이디, 비밀번호를 사용한 로그인 기능 구현
* 제품: 카테고리/개별 제품 조회 및 등록 기능 구현 
* 카트: 장바구니/구매 내역 기능 구현 

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 다양한 제품들을 어떻게 하면 가장 효율적으로 관리할 수 있을지 고민했습니다. 실무에서는 한 테이블 안에 모두 관리되도록 초기부터 
설계한다는 점을 알게 되었습니다. 

<br />

## :: 기타 질문 및 특이 사항
- 없습니다

2022-03-29 08:49 UTC, lordmyshepherd requested changes

2022-03-29 08:49 UTC, lordmyshepherd commented on carts/models.py
> +class Purchase(models.Model):
`Purchase` 보다는 `Order`라는 많이 사용하는 테이블 명으로 수정해주세요!

2022-03-29 08:49 UTC, lordmyshepherd commented on carts/models.py
> +    order          = models.ForeignKey('Purchase', on_delete=models.CASCADE)
cart가 order를 참고하지 않도록 수정해주세요. cart와 order는 참조 관계없이, 독립적으로 존재하도록 만들어주셔야 합니다!

2022-03-29 08:49 UTC, lordmyshepherd commented on carts/models.py
> +class Cart_State(models.Model):
`cart status`는 어떤 값들이 들어가나요?

2022-03-29 08:49 UTC, lordmyshepherd commented on products/models.py
> +        db_table = 'pictures'
`img`  -> `image_url` 혹은 `url`로 수정해주세요. 실제로 컬럼에 저장되는 값은 image_url 이기 때문에 컬럼 명도 명확하게 만들어주셔야 합니다.
```suggestion
class Picture(models.Model):
    product    = models.ForeignKey('Product', on_delete=models.CASCADE)
    url        = models.CharField(max_length=1000)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'pictures'
```

2022-03-29 09:00 UTC, mquat commented on carts/models.py
> +    order          = models.ForeignKey('Purchase', on_delete=models.CASCADE)
하나의 order에 여러 cart 제품이 포함되고, 새로 주문이 들어왔을 때는 새로운 order가 들어오므로(빈 cart 상태가 됨) 위와 같이 작성했는데 틀렸을까요 ㅜㅜ?

2022-03-29 09:02 UTC, mquat commented on carts/models.py
> +class Cart_State(models.Model):
주문 가능 여부(재고 상태에 따른) 정보가 들어가는 것으로 생각했습니다

2022-03-29 09:09 UTC, mquat commented on carts/models.py
> +    order          = models.ForeignKey('Purchase', on_delete=models.CASCADE)
그러니까 cart는 장바구니고, order는 주문 내용이니까 cart가 order를 참조해야 구매할 때 주문 내역(cart에 있는 내용) 을 불러올 수 있지 않나 하는 생각입니다~!

2022-03-29 11:27 UTC, lordmyshepherd commented on carts/models.py
> +    order          = models.ForeignKey('Purchase', on_delete=models.CASCADE)
주문을 할 때, 이 주문이 어떤 카트에 담긴 상품을 주문하는지 알고 있어야할 필요가 없습니다! 그렇기 때문에 카트와 주문은 독립적으로 관리해야해요.

카트는 주문 후에 지워질 데이터라는 점만 봐도 참조 관계가 필요 없음을 알 수 있어요!

2022-03-29 11:29 UTC, lordmyshepherd commented on carts/models.py
> +class Cart_State(models.Model):
카트의 상태까지 추가할 필요는 없을 것 같아요. 재고 확인 목적이라면 카트에 담는 요청이 있을때 재고를 확인해서 담으면 될 것 같아요!

2022-03-29 12:03 UTC, sangahnhan commented on carts/models.py
> +    order          = models.ForeignKey('Purchase', on_delete=models.CASCADE)
네 알겠습니다

2022-03-29 12:03 UTC, sangahnhan commented on carts/models.py
> +class Cart_State(models.Model):
넵 재고관리할 수 있게 모델링 수정하겠습니다

2022-03-30 01:49 UTC, mquat commented
1차 피드백 반영한 모델링 수정본 올렸습니다!

2022-03-30 01:56 UTC, closed without merging