Feature/users view
wecode-bootcamp-korea/31-1st-TheCreationOfWeb-backend pull request #9
Opened 2022-04-01 08:00 UTC by mquat

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- users앱/view - 회원정보조회 기능 추가 구현 

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- 회원정보 조회 기능 추가 구현 (회원이 마이페이지 클릭하면 자기 정보 확인할 수 있음) 

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항

2022-04-01 21:35 UTC, lordmyshepherd requested changes

2022-04-01 21:35 UTC, lordmyshepherd commented on users/views.py
> +        return JsonResponse({'message':result}, status=200)
**피드백 1.**
데이터를 기준으로 사용자 정보를 호출하는 엔드포인트로 만들어주셔야 합니다.
그러므로 class명도 "프로필 확인을 한다."이라는 느낌보다는 "사용자 정보 반환." 이라는 느낌으로 만들어주시는게 좋습니다.

이런 기준으로 만드셔야, 나중에 "사용자 정보 업데이트"가 필요한 경우 새로운 class를 만드는게 아니라 UserView class의 하위 method를 추가할 수 있습니다.
```python
# 예를 들면,
class UserView:
    def post
    def get #사용자 정보 호출
    def patch #사용자 정보 업데이트
    def delete # 사용자 정보 삭제

```

**피드백 2.** line 70 코드가 필요한지 다시한번 생각해보시면 좋을 것 같습니다.
```suggestion
class UserView(View):
    @login_decorator
    def get(self, request):
        result = {
            'name'         : user.name,
            'address'      : user.address,
            'phone_number' : user.phone_number,
            'amount'       : user.amount
        }

        return JsonResponse({'message':result}, status=200)
```

2022-04-02 03:10 UTC, mquat commented on users/views.py
> +        return JsonResponse({'message':result}, status=200)
네 병민님 주신 피드백 잘 살펴보고 수정해보겠습니다 감사합니다!

2022-04-02 05:25 UTC, mquat commented on users/views.py
> +        return JsonResponse({'message':result}, status=200)
병민님 해당 내용 제가 수정했는데, Line 70번 코드가 불필요한 이유를 정리하자면:
- login decorator에서 특정 user의 개인정보를 get해서 user라는 속성에 담아 request에 보내주고 (request.user),
- UserVeiw는 해당 정보를 받은 상태이기 때문에, 바로 user.name 처럼 작성해 특정 user의 정보를 호출할 수 있습니다. 
- 그래서 line 70은 별도 작성이 필요 없습니다. 

위와 같이 이해한 내용이 맞을까요?

2022-04-02 09:27 UTC, mquat commented
병민님, 아래와 같이 추가로 수정했습니다. 
- 회원정보조회 view 이름 수정 (UserView로 변경) 
- UserView의 Line 70: user = request.user로 변경 (이미 login_decorator에서, 해당 id의 정보를 get하는 함수까지 작성했기 때문에, 다시 쓸 필요 없고 request.user로  수정했습니다.) 
- models.py 속성 수정 (원래 계획대로 name은 다시 삭제함) 
- utils.py error 추가 설정 (jwt 유효기간이 지나면, ExpiredSignatureError를 return)

2022-04-02 09:30 UTC, lordmyshepherd requested changes

2022-04-02 09:30 UTC, lordmyshepherd commented on products/migrations/image_url_0401.csv
> +id,product_id,image_url
csv 파일은 github에 올라오지 않도록 .gitignore에 추가해주세요-!

2022-04-02 09:30 UTC, lordmyshepherd commented on products/views.py
> +class CategoryView(View):
해당 PR 목적과 맞지 않는 코드들은 전부 지워주세요-!

2022-04-02 09:57 UTC, mquat commented
지적하신 부분 수정했습니다, 확인 부탁 드립니다 병민님 ~!

2022-04-02 11:30 UTC, mquat commented
지적하신 부분 수정했습니다, 확인 부탁 드립니다 병민님 ~! (주말에도 피드백 주셔서 감사합니다 ㅜㅜ)
 - users앱/views 제외 다른 코드 삭제 
 - gitignore에 data.py 및 csv 파일 추가 
 - users앱/views.py 오타 수정

2022-04-04 01:28 UTC, lordmyshepherd requested changes

2022-04-04 01:28 UTC, lordmyshepherd commented on carts/models.py
> -class Cart(models.Model):
cart에 있는 models.py 코드를 전부 지우는게 맞는 건가요?

2022-04-04 01:28 UTC, lordmyshepherd commented on products/models.py
> -class Product(models.Model):
마찬가지로 products/models.py 코드를 전부 지우는 이유가 궁금합니다!

2022-04-04 02:26 UTC, mquat commented
안녕하세요 병민님 ~ products앱/carts앱 모델링 다시 추가했고, 제가 잘못 처리한데는 아래와 같은 이유가 있었습니다. 
- 'PR과 관계 없는 내용 제외' 에 대해 잘못 이해 
- git merge과정에 대해 부족했던 이해  
   - main 브랜치에 이미 반영된 내용을 삭제하면 삭제된 작업이 그대로 merge된다는 점을 간과함 
   - 제가 git을 다루는데 있어서 아직 부족한 부분이 있다보니, 잘못된 처리를 했습니다. 
   - 계속 git을 다루고 내용 찾아가며 보완해나가고 있습니다.

2022-04-04 05:46 UTC, lordmyshepherd requested changes

2022-04-04 05:46 UTC, lordmyshepherd commented on users/urls.py
> +    path('/mypage', UserView.as_view())
```suggestion
    path('/user', UserView.as_view())
```

2022-04-04 06:27 UTC, mquat commented
수정 완료했습니다 병민님 : )

2022-04-04 09:27 UTC, lordmyshepherd commented
LGTM 👍🏻

2022-04-04 09:27 UTC, merged